# Criar arquivo ~/.personal_password contendo sua senha de acesso ao host
- hosts: all
  become: False
  gather_facts: False
  serial: "30%"
  tasks:
    - name: Configure access to all inventory hosts via SSH using Public Key
      shell: |
        ssh-keygen -R {{ inventory_hostname }}
        sshpass -f ~/.personal ssh-copy-id -i ~/.ssh/id_rsa.pub -f -o StrictHostKeyChecking=no suporte@{{ inventory_hostname }}
      delegate_to: localhost
      ignore_errors: yes
