- hosts: web01
  become: true
  tasks:
    - name: DNS - Install package
      package:
        name:
          - bind9
          - dnsutils
        state: present

    - name: DNS - Enable service
      systemd:
        name: bind9
        enabled: yes

    - name: DNS - Editing resolv.conf
      template:
        src: resolv.conf
        dest: /etc/
        force: yes

    - name: DNS - Bind zone config
      template:
        src: named.conf.local.final
        dest: /etc/bind/named.conf.local
        owner: root
        group: bind
        mode: 0644

    - name: DNS - Bind zone options dexter
      template:
        src: named.conf.options
        dest: /etc/bind/named.conf.options
        owner: root
        group: bind
        mode: 0644

    - name: DNS - Bind zone dexter
      template:
        src: db.dexter
        dest: "/var/cache/bind/db.dexter"
        owner: bind
        group: bind
        mode: 0644

    - name: DNS - Bind zone reverse dexter
      template:
        src: rev.dexter
        dest: "/var/cache/bind/rev.dexter"
        owner: bind
        group: bind
        mode: 0644

    - name: DNS - Started service
      systemd:
        name: bind9
        state: restarted
