- hosts: security
  become: true
  tasks:
    - name: FIREWALL - Copy script
      copy:
        src: /opt/iptables/firewall
        dest: /etc/init.d/
        mode: 744

    - name: FIREWALL - Copy rules
      template:
        src: rules
        dest: /opt/iptables/
        mode: 644

    - name: FIREWALL - Service enable firewall
      service:
        name: firewall
        enabled: yes

    - name: FIREWALL - Service start firewall
      service:
        name: firewall
        state: started
